name: actions
on:
  push:
    branches:
      - main
name: actions
on:
  push:
   branches: [master]
  pull_request:
   branches: [master]
jobs: 
  build_Linux:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Adding gtest
     run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

   - name: Config ConceptualExample with tests
     run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

   - name: Build ConceptualExample
     run: cmake --build ${{github.workspace}}/build
